name: Deploy to Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Pull Latest Code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/html/your-app-directory
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/Hemanth2003m/Weather-API.git .
            fi
            sudo systemctl restart apache2
